# Generated by Django 3.2.14 on 2022-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produtovendedor',
            name='descricao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
