# Generated by Django 3.2.14 on 2022-10-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221008_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feira',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='uf',
        ),
        migrations.AddField(
            model_name='favoritoproduto',
            name='senha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritovendedor',
            name='senha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feira',
            name='data_evento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feira',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feira',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geolocalizacao',
            name='senha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='senha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritoproduto',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favoritovendedor',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='agrotoxico',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='geolocalizacao',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
