# Generated by Django 3.2.14 on 2022-11-06 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20221026_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritoproduto',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='favoritovendedor',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='geolocalizacao',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='senha',
        ),
        migrations.AlterField(
            model_name='favoritoproduto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritovendedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geolocalizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
