# Generated by Django 3.2.14 on 2022-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221106_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtovendedor',
            name='ter_ou_nao',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
